'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
type Key={time?:number;value?:number;x?:number;y?:number;name?:string|null};
type Rig={bones:{name:string;parent?:string;x:number;y:number}[];slots:{name:string;attachment?:string}[];skins:{attachments:Record<string,Record<string,{path:string;uvs:number[];triangles:number[];vertices:number[]}>>}[];animations:Record<string,{bones:Record<string,Record<string,Key[]>>;slots:Record<string,{attachment:Key[]}>}>};
function sample(keys:Key[]|undefined,t:number,field:'x'|'y'|'value',fallback=0){if(!keys?.length)return fallback;let i=0;while(i+1<keys.length&&(keys[i+1].time??0)<=t)i++;const a=keys[i],b=keys[Math.min(i+1,keys.length-1)];const f=Math.min(1,(t-(a.time??0))/((b.time??0)-(a.time??0)||1));return (a[field]??fallback)*(1-f)+(b[field]??fallback)*f;}
export default function NoctiaRoom({onBack}:{onBack:()=>void}){
 const host=useRef<HTMLDivElement>(null),control=useRef({clip:'idle',paused:false,zoom:1});
 const [clip,setClip]=useState('idle'),[paused,setPaused]=useState(false),[zoom,setZoom]=useState(1),[status,setStatus]=useState('正在準備 NOCTIA…'),[retry,setRetry]=useState(0);
 useEffect(()=>{control.current={clip,paused,zoom}},[clip,paused,zoom]);
 useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)setPaused(true)},[]);
 useEffect(()=>{
  const container=host.current!;let disposed=false,frame=0;const abort=new AbortController();let renderer:THREE.WebGLRenderer|undefined;const resources:{dispose:()=>void}[]=[];let observer:ResizeObserver|undefined;
  async function start(){try{
   const response=await fetch('./examples/noctia/animation.json',{signal:abort.signal});if(!response.ok)throw Error('animation');const rig:Rig=await response.json();if(disposed)return;
   renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;container.appendChild(renderer.domElement);
   const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-550,550,1536,0,.1,100);camera.position.z=10;
   const loader=new THREE.TextureLoader();
   const items=await Promise.all(rig.slots.map(async(slot,index)=>{const entry=Object.values(rig.skins[0].attachments[slot.name])[0];const tex=await loader.loadAsync('./examples/noctia/images/'+entry.path+'.png');resources.push(tex);tex.colorSpace=THREE.SRGBColorSpace;
    const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(entry.uvs.length/2*3),3));geometry.setAttribute('uv',new THREE.Float32BufferAttribute(entry.uvs.map((v,i)=>i%2?1-v:v),2));geometry.setIndex(entry.triangles);
    const material=new THREE.MeshBasicMaterial({map:tex,transparent:true,depthTest:false,depthWrite:false,side:THREE.DoubleSide});resources.push(geometry,material);const mesh=new THREE.Mesh(geometry,material);mesh.frustumCulled=false;mesh.renderOrder=index;scene.add(mesh);return {slot,entry,mesh};
   }));if(disposed){resources.forEach(r=>r.dispose());return;}
   const resize=()=>{if(!renderer)return;const {width,height}=container.getBoundingClientRect();renderer.setSize(Math.max(width,1),Math.max(height,1));};observer=new ResizeObserver(resize);observer.observe(container);resize();
   const parents=rig.bones.map(b=>rig.bones.findIndex(p=>p.name===b.parent));const matrices=rig.bones.map(()=>new THREE.Matrix4());const local=new THREE.Matrix4(),pos=new THREE.Vector3(),scale=new THREE.Vector3(),rotation=new THREE.Quaternion(),axis=new THREE.Vector3(0,0,1),point=new THREE.Vector3();let previous=performance.now(),time=0,active=control.current.clip;
   setStatus('');
   const draw=(now:number)=>{if(disposed||!renderer)return;const state=control.current;const delta=Math.min((now-previous)/1000,.05);previous=now;if(active!==state.clip){active=state.clip;time=0;}if(!state.paused&&!document.hidden)time=(time+delta)%8;const animation=rig.animations[active];
    rig.bones.forEach((bone,i)=>{const tracks=animation.bones[bone.name];pos.set(bone.x+sample(tracks?.translate,time,'x'),bone.y+sample(tracks?.translate,time,'y'),0);scale.set(sample(tracks?.scale,time,'x',1),sample(tracks?.scale,time,'y',1),1);rotation.setFromAxisAngle(axis,sample(tracks?.rotate,time,'value')*Math.PI/180);local.compose(pos,rotation,scale);matrices[i].copy(local);if(parents[i]>=0)matrices[i].premultiply(matrices[parents[i]]);});
    for(const {slot,entry,mesh} of items){let attachment=slot.attachment;for(const k of animation.slots[slot.name]?.attachment??[])if((k.time??0)<=time)attachment=k.name??undefined;mesh.visible=!!attachment;const array=mesh.geometry.attributes.position.array as Float32Array;let cursor=0,vertex=0;while(cursor<entry.vertices.length){const count=entry.vertices[cursor++];let x=0,y=0;for(let n=0;n<count;n++){const bone=entry.vertices[cursor++],px=entry.vertices[cursor++],py=entry.vertices[cursor++],weight=entry.vertices[cursor++];point.set(px,py,0).applyMatrix4(matrices[bone]);x+=point.x*weight;y+=point.y*weight;}array[vertex++]=x;array[vertex++]=y;array[vertex++]=0;}mesh.geometry.attributes.position.needsUpdate=true;}
    const aspect=container.clientWidth/Math.max(1,container.clientHeight),height=Math.max(1600,1040/aspect)/state.zoom,center=state.zoom>1?1070:768;camera.left=-height*aspect/2;camera.right=height*aspect/2;camera.top=center+height/2;camera.bottom=center-height/2;camera.updateProjectionMatrix();renderer.render(scene,camera);frame=requestAnimationFrame(draw);
   };frame=requestAnimationFrame(draw);
  }catch(error){if(!disposed&&!abort.signal.aborted)setStatus('載入失敗，請重試。')}}void start();
  return()=>{disposed=true;abort.abort();cancelAnimationFrame(frame);observer?.disconnect();resources.forEach(r=>r.dispose());renderer?.dispose();renderer?.domElement.remove();};
 },[retry]);
 return <main className="noctia-room"><header><button onClick={onBack}>← 角色列表</button><span>SUCCUBUS / MOONLIT LIBRARY</span><small>02 · NOCTIA</small></header><div className="noctia-layout"><aside><p className="eyebrow">THE NIGHT KEEPER</p><h1>NOCTIA<span>月夜圖書館管理員</span></h1><p>書頁翻動，夜色停留。<br/>在月光下，與她相遇。</p><dl><dt>年齡</dt><dd>25 歲</dd><dt>展示</dt><dd>2D 骨架動畫</dd></dl></aside><section className="noctia-stage" aria-label="NOCTIA 動態角色"><div className="noctia-moon"/><div ref={host} className="noctia-canvas"/>{status&&<div className="noctia-status" role="status">{status}{status.includes('失敗')&&<button onClick={()=>{setStatus('正在準備 NOCTIA…');setRetry(r=>r+1)}}>重新載入</button>}</div>}<span className="noctia-stage-label">NOCTIA · {clip==='idle'?'IDLE':'HAND TO HEART'}</span></section><aside className="noctia-controls"><p className="eyebrow">MOMENTS</p><h2>她的片刻</h2><button aria-pressed={clip==='idle'} onClick={()=>setClip('idle')}>01 <span>靜靜陪伴<small>呼吸 · 眨眼 · 髮絲微動</small></span></button><button aria-pressed={clip==='hand_to_chest'} onClick={()=>setClip('hand_to_chest')}>02 <span>手放心前<small>抬手 · 停留 · 放下</small></span></button><div className="noctia-tools"><button aria-pressed={paused} onClick={()=>setPaused(p=>!p)}>{paused?'▶ 播放':'Ⅱ 暫停'}</button><button aria-pressed={zoom>1} onClick={()=>setZoom(z=>z>1?1:1.65)}>{zoom>1?'全身':'近看'}</button></div><p className="noctia-note">動作循環播放。<br/>可以暫停，細看每個瞬間。</p></aside></div></main>;
}
